apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customerapi.fullname" . }}
  labels:
    {{- include "customerapi.labels" . | nindent 4 }}
type: Opaque
data:
  # Add your key-value pairs here