apiVersion: v2
name: customer-api
description: A Helm chart for Kubernetes to deploy the Customer API application
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - api
  - customer
home: https://192.168.68.155/customer-api
sources:
  - https://github.com/example/customer-api
maintainers:
  - name: Narayan Ambatipudi
    email: narayan.avs@gmail.com
    url: https://github.com/nambatipudi/CustomerApi